import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Chat from './chat'
import Input from './input'
import { useState, useEffect } from 'react'
import { io } from 'socket.io-client'
import { v4 as uuidv4 } from 'uuid';

const inter = Inter({ subsets: ['latin'] })

let socket: any;

export interface Message  {
  author: string;
  message: string;
  id: string;
};

export default function Home() {

  const [chosenUsername, setChosenUsername] = useState("test");
  const [messages, setMessages] = useState<Array<Message>>([]);

  useEffect(() => {
    const socketInitializer = async () => {
      await fetch("/api/socket");
      socket = io();
  
      const eventHandle = (msg: { author: any; message: any, id: string }) => {
     
      
        setMessages((currentMsg) => {
          
          if(currentMsg?.some((oldMsg) => oldMsg?.id === msg?.id)){
            return [...currentMsg]
          }
          return [
          ...currentMsg,
          { author: msg.author, message: msg.message, id: msg.id},
        ]});
      }
  
      socket.on("newIncomingMessage", eventHandle);
    }
  
    socketInitializer();

    return () => {
      if(!!socket){
        socket.off("newIncomingMessage")
      }
    }
  }, []);


  const sendMessage = async (message: string) => {
    socket.emit("createdMessage", { author: chosenUsername, message, id: uuidv4() } as Message);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Chat messages={messages}/>
        <Input onSend={sendMessage}/>
      </main>
    </>
  )
}
